### ISSUE TITLE
Block 'default-shelf' interface errors

### ISSUE THREAD

**Issue by landif** [vtex-apps/recommendation-shelf#20] opened 2020-12-09 15:31 UTC
**Describe the bug**
If recommendation shelf is defined has the documentation example:
`
"store.home": {
    "blocks": [
      "flex-layout.row#recommendation-shelf",
    ]
  },
  "flex-layout.row#recommendation-shelf": {
    "children": ["recommendation-shelf"]
  },
  "recommendation-shelf": {
    "blocks": ["default-shelf"]
  },
  "default-shelf": {
    "blocks": ["list-context.product-list"]
  },
  "list-context.product-list": {
    "blocks": ["product-summary.shelf#demo1"],
    "children": ["slider-layout#demo-products"]
  },
  "product-summary.shelf#demo1": {
    "children": [
      "stack-layout#prodsum",
      "product-summary-name",
      "product-rating-inline",
      "product-summary-space",
      "product-summary-price",
      "product-summary-buy-button"
    ]
  },
  "slider-layout#demo-products": {
    "props": {
      "itemsPerPage": {
        "desktop": 5,
        "tablet": 3,
        "phone": 1
      },
      "infinite": true,
      "fullWidth": false
    }
  }
`

Building errors occur
`12:03:00.808 - error: App build failed with message: Block 'default-shelf' implements interface 'vtex.shelf-components@0.x:default-shelf'. It should contain at least one block that implements 'vtex.product-summary@2.x:list-context.product-list-static but none of it's blocks do.  
12:03:00.818 - error: Block 'default-shelf' implements interface 'vtex.shelf-components@0.x:default-shelf'. It should contain at least one block that implements 'vtex.product-summary@2.x:list-context.product-list-static but none of it's blocks do. vtex.builder-hub@0.270.1  
`
If list-context.product-list-static is defined in block:

`12:07:31.960 - error: App build failed with message: Block 'default-shelf' implements interface 'vtex.shelf-components@0.x:default-shelf'. It should contain at least one block that implements 'vtex.product-summary@2.x:list-context.product-list but none of it's blocks do.  
12:07:31.965 - error: Block 'default-shelf' implements interface 'vtex.shelf-components@0.x:default-shelf'. It should contain at least one block that implements 'vtex.product-summary@2.x:list-context.product-list but none of it's blocks do. vtex.builder-hub@0.270.1  
`

If list-context.product-list-static  and  list-context.product-list are defined in block, the shelf returns with no products....

**To Reproduce**

Use the documentation example

**Desktop environment:**

**Comment by leomuzicarvalho** [comment] 2020-12-14 13:35
I'm having the same problem when I try:

`"shelf.relatedProducts":{
    "props":{
      "productList":{
        "titleText": "Outras cores"
      }
    }
  },`

If I remove this implementation, it works fine and shows my products, but with undesired info.

**Comment by landif** [comment] 2020-12-14 13:56
> shelf.relatedProducts

shelf.relatedProducts and recommendation-shelf are two different components. You look at shelf component repo for answers.

**Comment by crisvtex** [comment] 2021-04-26 19:15
We are facing same errors related to default-shell

`error: App build failed with message: Block 'recommendation-shelf' implements interface 'vtex.recommendation-shelf@1.x:recommendation-shelf'. It should contain at least one block that implements 'vtex.shelf-components@0.x:default-shelf but none of it's blocks do.  
13:42:59.247 - error: Block 'recommendation-shelf' implements interface 'vtex.recommendation-shelf@1.x:recommendation-shelf'. It should contain at least one block that implements 'vtex.shelf-components@0.x:default-shelf but none of it's blocks do.`

**Comment by thalytafabrine** [comment] 2021-04-26 20:41
I'm closing this issue because it is not a bug. 
As described in the error, if you are declaring a `recommendation-shelf` block, that block must contain the blocks that are required for it, in this case the `default-shelf` as you can see here:
https://github.com/vtex-apps/recommendation-shelf/blob/master/store/interfaces.json#L4
Same for `default-shelf`. It should contain the blocks `list-context.product-list` and `list-context.product-list-static` that are required for it.

Example from our documentation:
![image](https://user-images.githubusercontent.com/20840671/116147848-96d91580-a6b6-11eb-87f5-e2233a69d630.png)

**Closed by thalytafabrine** 2021-04-26 20:41 UTC
Labels: bug
